## 1. Write a program to generate 6 digit random secure OTP.

In [15]:
import random

def ques1():
    i = 0
    res = ""
    while (i < 6):
        randDigit = random.randint(0, 9)
        res += str(randDigit)
        i += 1
    return int(res)
    
print("The Random generated OTP is", ques1())

The Random generated OTP is 941467


## 2. Write a program to pick a random character from a given String supplied by the user.

In [20]:
import random 

def ques2(string):
    ranIdx = random.randint(0, len(string)-1)
    print(f"The random character is {string[ranIdx]}")

string = input("Enter String: ")
ques2(string)

Enter String:  qw


The random character is w


## 3. Write a program to generate a random Password which meets the following conditions
## a. Password length must be 10 characters long.
## b. It must contain at least 2 upper case letters, 1 digit, and 1 special symbol.

In [24]:
import random

def ques3(length=10):
    
    upper_case = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    lower_case = "abcdefghijklmnopqrstuvwxyz"
    digits = "0123456789"
    special_symbols = "!@#$%^&*()-_=+[]{}|;:',.<>?/`~"
    
    password = [
        random.choice(upper_case),
        random.choice(upper_case),
        random.choice(digits),
        random.choice(special_symbols)
    ]
    
    all_characters = upper_case + lower_case + digits + special_symbols
    password += random.choices(all_characters, k=length-4)

    random.shuffle(password)
    return ''.join(password)


print("The Random passowrd is", ques3())

The Random passowrd is ~Bd74y4~P(


## 4. Given a two list of numbers, write a program to create a new list such that the new list should contain odd numbers from the first list and even numbers from the second list

In [26]:
def ques4(lst1, lst2):
    EvenOddLst = []
    for x, y in zip(lst1, lst2):
        if x % 2 != 0:
            EvenOddLst.append(x)
        if y % 2 == 0:
            EvenOddLst.append(y)
    return EvenOddLst

# Read input and convert to lists of integers
lst1 = list(map(int, input("Enter numbers with spaces for list 1: ").split()))
lst2 = list(map(int, input("Enter numbers with spaces for list 2: ").split()))

print(ques4(lst1, lst2))

Enter numbers with spaces for list 1:  1 2 3 4 5 6 7 8 9
Enter numbers with spaces for list 2:  11 22 3 34 45 5 6 6 7 7


[1, 22, 3, 34, 5, 7, 6, 6, 9]


## 5. Write a program to create a numpy array and return array of odd rows and even columns from the numpy array.


In [9]:
import numpy as np

def create_array(rows, cols):
    array = np.arange(1, rows * cols + 1).reshape(rows, cols)
    return array

def odd_rows_even_cols(array):
    print("Odd Rows:")
    print(array[::2])
    print("Even Columns:")
    print(array[:,1::2])

if __name__ == "__main__":
    rows = int(input("Enter the number of rows: "))
    cols = int(input("Enter the number of columns: "))

    array = create_array(rows, cols)

    print("Original Array:")
    print(array)
    print("\nArray of odd rows and even columns:")
    odd_rows_even_cols(array)

Enter the number of rows:  5
Enter the number of columns:  5


Original Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Array of odd rows and even columns:
Odd Rows:
[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]
Even Columns:
[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]
 [22 24]]


## Write a program create a numpy array and sort as per below cases:
## a. Case 1: Sort array by the second row.
## b. Case 2: Sort the array by the second column

In [3]:
import numpy as np

def create_array(rows, cols):
    array = np.random.randint(1, 100, size=(rows, cols))
    return array

def sort_by_second_row(array):
    return array[:, array[1, :].argsort()]

def sort_by_second_column(array):
    return array[array[:, 1].argsort()]

if __name__ == "__main__":
    rows = int(input("Enter the number of rows: "))
    cols = int(input("Enter the number of columns: "))

    array = create_array(rows, cols)

    print("Original Array:")
    print(array)

    # Sort by the second row
    sorted_by_row = sort_by_second_row(array)
    print("\nArray sorted by the second row:")
    print(sorted_by_row)

    # Sort by the second column
    sorted_by_column = sort_by_second_column(array)
    print("\nArray sorted by the second column:")
    print(sorted_by_column)

Enter the number of rows:  3
Enter the number of columns:  3


Original Array:
[[21 42 53]
 [99 68 52]
 [21 77 60]]

Array sorted by the second row:
[[53 42 21]
 [52 68 99]
 [60 77 21]]

Array sorted by the second column:
[[21 42 53]
 [99 68 52]
 [21 77 60]]
